server:
  port: 80
  
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/autotrade
    username: root
    password: root
    driverClassName: com.mysql.jdbc.Driver

appSettings:
  cp: oanda
  symbol: USD/JPY
  
  fix:
    # ログオンメッセージのヘッダーに設定するパスワード
    password: ${appSettings.fix.password}
    # オーダーで設定する口座番号
    account: ${appSettings.fix.account}
    # CPが気配値のプライスであることを示す文字列
    indicativeText: Indicative
    # サブスクライブチェック間隔
    subscribeCheckInterval: 60
    # 無配信閾値
    delayThreshold: 60
    
  trade:
    # レンジの上限
    uppoerLimit: 120
    # レンジの下限
    lowerLimit: 75
    # 1トラップの注文金額
    orderAmount: 100
    # トラップ値幅
    trapRange: 0.1
    # トラップの境界
    trapTiming: 0.07